.TH yandex-messenger 1 "April 2026" "2.155.0" "Yandex Messenger Native"
.SH NAME
yandex-messenger \- native Linux client for Yandex Messenger
.SH SYNOPSIS
.B yandex-messenger
.SH DESCRIPTION
Yandex Messenger Native is a Rust and GTK based desktop client for messaging,
file sharing, and Telemost calls.
.SH OPTIONS
No command line options are currently supported.
.SH AUTHOR
BeZoom
